//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9LinqToSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public string course_code { get; set; }
        public string course_name { get; set; }
        public string credit_hours { get; set; }
        public string duration { get; set; }
        public string course_level { get; set; }
        public string prerequisites { get; set; }
        public string course_fee { get; set; }
        public string instructor_name { get; set; }
    }
}
