//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A9LinqToSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string experience { get; set; }
        public string type { get; set; }
        public string address { get; set; }
        public string date_of_birth { get; set; }
        public string date_of_joining { get; set; }
    }
}
