//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL_Exam_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int id { get; set; }
        public string type_of_furniture { get; set; }
        public string color { get; set; }
        public int seating_capacity { get; set; }
    }
}
